[general]
    name = "Mi Band"
    nameRegex = "Google Pixel 5.*"
    type = "band"
    characteristicNames = ["heartRate"]
[heartRate]
name = "Heart Rate"
serviceUUID = "0000180d-0000-1000-8000-00805f9b34fb"
characteristicUUID = "00002a37-0000-1000-8000-00805f9b34fb"
